services:
#    gsadmin.example:
#        class: GS\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    gsadmin.menu.builder:
        class: GS\AdminBundle\Menu\Builder
        arguments: [ '@knp_menu.factory', '@doctrine.orm.entity_manager' ]
        tags:
            - { name: knp_menu.menu_builder, method: mainMenu, alias: mainMenu }
            - { name: knp_menu.menu_builder, method: organizerMenu, alias: organizerMenu }
            - { name: knp_menu.menu_builder, method: treasurerMenu, alias: treasurerMenu }
            - { name: knp_menu.menu_builder, method: secretaryMenu, alias: secretaryMenu }
            - { name: knp_menu.menu_builder, method: adminMenu, alias: adminMenu }

    gsadmin.profiler.admin.matcher:
        class: GS\AdminBundle\Profiler\AdminMatcher
        arguments: ['@security.authorization_checker']
        public: false

#    gsadmin.form.user.registration:
#        class: GS\AdminBundle\Form\Type\UserRegistrationType
#        tags:
#            - { name: form.type, alias: gsadmin_user_registration }
#
#    gsadmin.form.user.profile:
#        class: GS\AdminBundle\Form\Type\UserProfileType
#        tags:
#            - { name: form.type, alias: gsadmin_user_profile }

    # It is an event subscriber, not an event listener! To be corrected to avoid confusion
    gsadmin.user.listener:
        class: GS\AdminBundle\EventListener\UserListener
        arguments:
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    gsadmin.account_balance:
        class: GS\AdminBundle\Services\AccountBalanceService
        arguments: [ '@doctrine.orm.entity_manager' ]

#    gsadmin.user.repository:
#            class: Doctrine\ORM\EntityRepository
#            factory: ["@doctrine.orm.entity_manager", getRepository]
#            arguments:
#                - GS\AdminBundle\Entity\User

    gsadmin.event.table_prefix_subscriber:
        class: GS\AdminBundle\EventSubscriber\TablePrefixSubscriber
        public: false
        arguments: ['']
        tags:
            - { name: doctrine.event_subscriber }

    gsadmin.user.membership:
        class: GS\AdminBundle\Services\MembershipService
        arguments: [ '@doctrine.orm.entity_manager' ]

    gsadmin.registration.service:
        class: GS\AdminBundle\Services\RegistrationService
        arguments: [ '@doctrine.orm.entity_manager', '@mailer', '@lexik_mailer.message_factory' ]

    gsadmin.payment.service:
        class: GS\AdminBundle\Services\PaymentService
        arguments: [ '@mailer', '@lexik_mailer.message_factory' ]
