magephp:
    log_dir: /path/for/logs
    composer:
        path: /path/to/composer.phar
    environments:
        production:
            rsync: -avz --delete-after
            bin_path: '/usr/local/php5.6/bin:$PATH'
            user: user
            branch: master
            host_path: /path/on/host
            releases: 4
            symfony: { env: 'prod' }
            exclude:
                - ./var/cache/*
                - ./var/log/*
                - ./web/app_dev.php
            hosts:
                - localhost
            pre-deploy:
                - git/update
                - composer/self-update
                - composer/install: { flags: '--no-dev', timeout: 240 }
            on-deploy:
                - fs/copy: { from: '/path/on/host/parameters_prod.yml', to: 'app/config/parameters.yml', flags: '' }
                - fs/link: { from: '../../data/images', to: 'web/images', flags: '-sf' }
                - fs/link: { from: '../../data/files', to: 'web/files', flags: '-sf' }
                - symfony/cache-clear
                - symfony/cache-warmup
                - symfony/assets-install
                - symfony/assetic-dump
            on-release:
            post-release:
            post-deploy:
        test:
            rsync: -avz --delete-after
            bin_path: '/usr/local/php5.6/bin:$PATH'
            user: user
            branch: master
            host_path: /path/on/host
            releases: 4
            symfony: { env: 'dev' }
            exclude:
                - ./var/cache/*
                - ./var/log/*
            hosts:
                - localhost
            pre-deploy:
                - git/update
                - composer/self-update
                - composer/install: { timeout: 240 }
            on-deploy:
                - fs/copy: { from: '/path/on/host/parameters_dev.yml', to: 'app/config/parameters.yml', flags: '' }
                - fs/move: { from: 'web/app_dev.php', to: 'web/app.php' }
                - fs/link: { from: '../../data/images', to: 'web/images', flags: '-sf' }
                - fs/link: { from: '../../data/files', to: 'web/files', flags: '-sf' }
                - symfony/cache-clear
                - symfony/cache-warmup
                - symfony/assets-install
                - symfony/assetic-dump
            on-release:
            post-release:
            post-deploy:
