imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

framework:
    #esi:             ~
    translator:      { fallbacks: [en, fr]}
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    serializer:
        enabled: false
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - 'GSApiBundle::jquery.collection.html.twig'
        - 'VichUploaderBundle:Form:fields.html.twig'
        # - 'bootstrap_3_horizontal_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: %mysql_server_version%
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    auth_mode: "%mailer_auth_mode%"
    host:      "%mailer_host%"
    encryption: "%mailer_encryption%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'

lexik_mailer:
    admin_email: %admin_email%
    templating_extensions:
        - 'twig.extension.trans' # load the translation extension

fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    serializer:
        serialize_null:  true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: GS\ApiBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        form:
            type: GS\ApiBundle\Form\Type\UserRegistrationType
    profile:
        form:
            type: GS\ApiBundle\Form\Type\UserProfileType

kmj_pay_pal_bridge:
    environment: sandbox
    sandbox:
        clientId: '%paypal_sandbox_client_id%'
        secret: '%paypal_sandbox_secret%'
    production:
        clientId: '%paypal_prod_client_id%'
        secret: '%paypal_prod_secret%'
    logs:
        enabled: true
        filename: '%kernel.root_dir%/../var/logs/paypal.log'
        level: FINE
    http:
        timeout: 30
        retry: true

assetic:
    debug:          '%kernel.debug%'
    filters:
        cssrewrite: ~
        jsqueeze:   ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'

# Using default values
doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

knp_snappy:
    temporary_folder: %kernel.cache_dir%/snappy
    pdf:
        enabled:    true
        binary:     %wkhtmltopdf.binary%
        options:    []

vich_uploader:
    db_driver: orm

    mappings:
        account_image:
            uri_prefix:         '%vich_uri_prefix%/images/account'
            namer:              vich_uploader.namer_uniqid
            upload_destination: '%kernel.root_dir%/../web/images/account'
        certificate_file:
            uri_prefix:         '%vich_uri_prefix%/files/certificate'
            namer:              vich_uploader.namer_uniqid
            upload_destination: '%kernel.root_dir%/../web/files/certificate'

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            timestampable: true

dizda_cloud_backup:
    # By default backup files will have your servers hostname as prefix
    # such as: hostname_2014-01-01_21-08-39.tar
    output_file_prefix: hostname
    timeout: 300
    restore: true
    processor:
        type: tar
        options:
            compression_ratio: 6
            password: qwerty
    cloud_storages:
        # Local storage definition
        local:
            path: '%kernel.root_dir%/../../backups'
    databases:
        mysql: ~
