# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext

        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_MEMBER:        ROLE_USER
        ROLE_PRIVILEGED:    ROLE_USER
        ROLE_SECRETARY:     ROLE_PRIVILEGED
        ROLE_TREASURER:     ROLE_PRIVILEGED
        ROLE_TOPIC_MANAGER: ROLE_PRIVILEGED
        ROLE_ORGANIZER:     ROLE_TOPIC_MANAGER
        ROLE_ADMIN:         [ROLE_TREASURER, ROLE_SECRETARY, ROLE_ORGANIZER]
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern:   ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: true
                default_target_path: /

            logout:       true
            anonymous:    true
            switch_user:
                role: ROLE_ADMIN
                # default value _switch_user
                parameter: _switch_user

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*, role: ROLE_USER }
